data = {
    "ids": [
        {
            "id": 1,
            "requisition_no": "001",
            "department": "Administration",
            "designation": "Human Resources Manager",
            "position_type": "Not specified",
            "contract_type_id": 1,
            "gender": "male",
            "date": datetime.date(2024, 12, 22),
            "approved_man": 0,
            "actual_man": 1,
            "request_man": 2,
            "est_salary": 20000.0,
            "act_salary": 0.0,
            "expertise": "fresh",
            "exp_year": 0,
            "edu_qual": "Educational Qualification",
            "requirements": "Provide some details regarding the type of employee required, as well as the qualifications and work experience, and any other factors which need to be considered\n",
            "is_parttime": True,
            "is_desc_exist": True,
            "is_reduce_mp": True,
            "is_fucn_effective": True,
            "is_cost_reduce": True,
            "is_internal": True,
            "prospects": "Not specified",
            "investigations": "Not specified",
            "commencement_date": datetime.date(2024, 12, 22),
            "have_mobile_allowance": True,
            "need_computer": True,
            "proposed_salary": 300000.0,
            "have_travel_allowance": True,
            "need_lunch": True,
            "other_benefits": "Other benefits (please specify)\n",
            "probation_name": "Unknown",
            "internal_transfer": True,
            "required_training": True,
            "training_name": "Unknown",
            "training_details": "Specify the required Training details\n",
            "requested_designation": "Chief Executive Officer",
            "authorized_designation": "Chief Executive Officer",
            "recommended_designation": "Chief Executive Officer",
            "approved_designation": "Chief Executive Officer",
        }
    ],
    "other": {
        "form_no": "001",
        "requisition_dept": "Administration",
        "requisition_company": "My Company (San Francisco)",
    },
}


test = {
    "context": {
        "lang": "en_US",
        "tz": "Asia/Dhaka",
        "uid": 2,
        "allowed_company_ids": [1],
        "params": {
            "id": 1,
            "cids": 1,
            "menu_id": 763,
            "action": 1054,
            "model": "hr.employee.requisition",
            "view_type": "form",
        },
        "active_model": "hr.employee.requisition",
        "active_id": 1,
        "active_ids": [1],
        "webp_as_jpg": True,
        "debug": False,
        "company": res.company(
            1,
        ),
        "company_name": "My Company (San Francisco)",
        "company_street": "250 Executive Park Blvd, Suite 3400",
        "company_street2": False,
        "company_city": "San Francisco",
        "company_zip": "94134",
        "company_phone": "+1 555-555-5556",
        "company_website": "http://www.example.com",
    },
    "doc_ids": [1],
    "doc_model": "hr.employee.requisition",
    "data": [
        {
            "id": 1,
            "requisition_no": "001",
            "department": "Administration",
            "designation": "Human Resources Manager",
            "position_type": "Not specified",
            "contract_type_id": 1,
            "gender": "male",
            "date": datetime.date(2024, 12, 22),
            "approved_man": 0,
            "actual_man": 1,
            "request_man": 2,
            "est_salary": 20000.0,
            "act_salary": 0.0,
            "expertise": "fresh",
            "exp_year": 0,
            "edu_qual": "Educational Qualification",
            "requirements": "Provide some details regarding the type of employee required, as well as the qualifications and work experience, and any other factors which need to be considered\n",
            "is_parttime": True,
            "is_desc_exist": True,
            "is_reduce_mp": True,
            "is_fucn_effective": True,
            "is_cost_reduce": True,
            "is_internal": True,
            "prospects": "Not specified",
            "investigations": "Not specified",
            "commencement_date": datetime.date(2024, 12, 22),
            "have_mobile_allowance": True,
            "need_computer": True,
            "proposed_salary": 300000.0,
            "have_travel_allowance": True,
            "need_lunch": True,
            "other_benefits": "Other benefits (please specify)\n",
            "probation_name": "Unknown",
            "internal_transfer": True,
            "required_training": True,
            "training_name": "Unknown",
            "training_details": "Specify the required Training details\n",
            "requested_designation": "Chief Executive Officer",
            "authorized_designation": "Chief Executive Officer",
            "recommended_designation": "Chief Executive Officer",
            "approved_designation": "Chief Executive Officer",
        }
    ],
    "other": {
        "form_no": "001",
        "requisition_dept": "Administration",
        "requisition_company": "My Company (San Francisco)",
    },
    "docs": hr.employee.requisition(
        1,
    ),
}
