{
    'name': "Custom HR Employee",
    'version': "1.0.0",
    'category': "Employee Information",
    'sequence': 1,
    'summary': "Customization of 'hr_employee' module for Odoo v17",
    'description': """Customization of 'hr_employee' module for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': [
        'base',
        'hr',
        'custom_stock',
        'hr_contract',
        'hr_skills',
        'hr_recruitment',
        'hr_timesheet',
        'custom_common_settings',
        'crm',
    ],
    'data': [
        'data/hr_resume_data.xml',
        'data/probation_schedule.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'data/hr_sequence_views.xml',
        'views/hr_details.xml',
        'views/hr_employee_contact_relation_view.xml',
        'reports/hr_employee_badge_custom.xml',
        'views/inherited_hr_employee_views.xml',
        'views/probation_period_views.xml',
        'views/hr_employee_type_view.xml',
        'views/hr_bank_views.xml',
        'views/hr_update_employee_promotion_demotion_redesignation_views.xml',
        'reports/employee_list_report_views.xml',
        # 'views/inherited_hr_department_views.xml',
        'views/hr_job_level_views.xml',
        'views/hr_job_grade_type_views.xml',
        'views/hr_job_grade_views.xml',
        'views/hr_dis_view.xml',
        'data/hr_disciplinary.xml',
        'views/hr_designation_job_grade_views.xml',
        'reports/employee_details_report_view.xml',
        'reports/employee_personal_data_sheet.xml',
        'reports/employee_badge_print.xml',
        'wizard/employee_confirmation_wizard.xml',
        # 'reports/report_attendance_list.xml',
        # 'views/inherited_hr_resume_line_views.xml',
        'views/hr_documents_view.xml',
        'views/hr_contract_days_inherited_views.xml',
        'data/hr_notification_views.xml',
        # 'views/updation_config_views.xml',
        'wizard/map_employee_wizard_views.xml',
        'wizard/employee_upload_wizard_views.xml',
        'wizard/employee_rejoining_wizard_views.xml',
        'views/hr_employee_disciplinary_type_views.xml',
        'views/reporting_manager_update_views.xml',
        'views/attendance_reprocess_dates_views.xml',
        'views/employee_iom_views.xml',
        'views/employee_training_views.xml',
        'views/hr_sbu_unit.xml',
        'wizard/employee_badge_print_wizard_views.xml',
        # 'views/print_badge_wizard_views.xml',
        # 'views/inherited_hr_employee_public.xml',
        'views/inherited_res_partner_inherit_hr_views.xml',
        'views/crm_lead_view_inherit.xml',

    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False
}
