{
    'name': 'Custom HR Final Settlement',
    'version': "1.0.0",
    'category': "Human Resources",
    'sequence': 1,
    'summary': "Handle the final settlement process of the employee for Odoo v17",
    'description': """Handle the final settlement process of the employee for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['hr_resignation', 'wppf', 'dev_hr_loan'],
    'data': [
        'views/emp_clearance_views.xml',
        'views/inherited_hr_employee_inherit_hr_settlement_views.xml',
        'views/emp_clearance_seq.xml',
        'security/ir.model.access.csv',
        'views/final_settlement_settings_views.xml',
        'views/employee_pf_settlement_views.xml',
        'views/employee_wppf_settlement_views.xml',
        'report/final_clearance_report_tmpl.xml',
        'report/final_settlement_sheet_tmpl.xml',
        'report/final_pf_settlement_sheet_tmpl.xml',
        'report/pf_final_settlement_report.xml',
        'report/wppf_final_settlement_report.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
