from . import date_wise_late_report
from . import one_time_punch_summary_report
from . import attendance_summary_report
from . import new_employee_recruitment_report
from . import employee_migration_report
from . import employee_detail_salary_sheet
from . import department_wise_employee_salary_summary_sheet
from . import employee_resign_report_wizard
from . import employee_advance_salary_summary_report_wizard
from . import loan_report_wizard
from . import night_food_allowance_report_wizard
from . import month_wise_lefty_report_wizard
from . import area_deduct_adjust_salary_report_wizard
from . import employee_resign_salary_sheet_wizard
from . import employee_salary_sheet_report
from . import date_wise_late_early_report
from . import employee_pf_report_wizard
from . import daily_attendance_sheet_wizard
from . import employee_overtime_report_wizard
from . import location_wise_employee_salary_summary_report_wizard
from . import employee_length_of_service_report
from . import employee_pf_details_report
from . import employee_pf_summery_report
from . import probationary_employee_report_wizard
from . import employee_leave_encashment_wizard
from . import unallocated_leave_report_wizard
from . import fringe_benefits_report_wizard
from . import employee_leave_report_wizard
from . import employee_confirmation_report_wizard
from . import salary_details_sheet
from . import month_wise_employee_pf_report_wizard
from . import month_wise_employee_loan_report_wizard
from . import employee_extra_office_time_report_wizard
from . import leave_emp_attendance_sheet_wizard
