{
    'name': 'Custom HR Advance Salary',
    'version': "17.0.0.0.1",
    'category': "Human Resources",
    'sequence': 1,
    'summary': "HR Advance Salary for Odoo v17",
    'description': """Helps you to manage Advance Salary Request of your company's staff for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['hr_payroll', 'dev_hr_loan'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/salary_advance.xml',
        'views/salary_structure.xml',
        'views/salary_advance_settings_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
