from . import crm_channel
from . import crm_communication_tag
from . import crm_quick_reply
from . import crm_sla
from . import crm_omni_utils
from . import crm_assignment_rule
from . import crm_csat_mixin
from . import crm_chat_message
from . import crm_chat_session
from . import crm_call_recording
from . import crm_call_log
from . import crm_communication
from . import crm_response_time
from . import crm_dashboard
from . import crm_chat_context
from . import crm_lead
from . import res_users
from . import res_partner
