# -*- coding: utf-8 -*-
# Copyright (c) Nelsis Tech. All Rights Reserved.
# Developer: Nur Uddin Ahammed
{
    'name': 'FW AI Assistant - Footwear ERP',
    'version': '17.0.1.0.0',
    'category': 'Manufacturing/Footwear',
    'summary': 'Rule-based risk detection and reorder recommendations across order '
                'delivery, machine reliability, supplier quality, and spare stock.',
    'description': """
FW AI Assistant
==================
Phase 5 module of the Nelsis Footwear ERP platform (Odoo Community 17).

HONEST SCOPE NOTE: This module is deliberately built as transparent,
deterministic, rule-based heuristic scoring over your existing FW data -
NOT a trained machine learning model. There is no model file, no
training data pipeline, and no statistical prediction here; every alert
this module raises is generated by an explicit, readable business rule
(see the _run_* methods on fw.ai.scan), so a user can always see exactly
why an alert fired. This is the honest and practical choice: a real ML
model needs historical labeled data, a training/validation process, and
ongoing monitoring that cannot be responsibly fabricated inside a code
deliverable. If genuine predictive ML is wanted later, this module's
alert structure is a reasonable foundation to plug a real model into.

Features
--------
* Order Delay Risk: flags Buyer Orders with delayed TNA milestones
  relative to their required ship date
* Machine Reliability Risk: flags machines with repeated breakdowns in
  a trailing window, or currently unresolved breakdowns
* Supplier Quality Risk: flags suppliers whose latest confirmed
  Scorecard grade is C or D
* Spare Stock Risk: flags spare parts below reorder level, with a
  simple suggested reorder quantity (buffer-based rule, not a forecast)
* All alerts are grouped under an auditable Scan run, with an
  acknowledge/resolve workflow

Author: Nur Uddin Ahammed
Copyright: Nelsis Tech
""",
    'author': 'Nur Uddin Ahammed (Nelsis Tech)',
    'company': 'Nelsis Tech',
    'maintainer': 'Nelsis Tech',
    'website': 'https://www.nelsistech.com',
    'license': 'OPL-1',
    'depends': ['fw_core_master', 'fw_merchandising', 'fw_cmms', 'fw_supplier', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/fw_ai_sequence.xml',
        'views/fw_risk_alert_views.xml',
        'views/fw_ai_scan_views.xml',
        'views/fw_ai_menus.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
