from . import hr_employee_type
from . import hr_disciplinary
from . import inherited_hr_employee
from . import probation_period
from . import inherited_res_partner
from . import inherited_hr_department
from . import inherited_hr_job_designation
from . import hr_job_level
from . import hr_job_grade_type
from . import hr_job_grade_line
from . import hr_job_grade
from . import hr_bank
from . import inherited_hr_resume_line
from . import hr_employee_contact_relations
from . import hr_documents
from . import hr_contract_days_inherited
from . import updation_config_inherited
from . import hr_employee_disciplinary_type
from . import inherited_res_users_inherit_custom_hr_employee
from . import reporting_manager_update
from . import attendance_reprocess_dates
from . import hr_update_employee_promotion_demotion_dedesignation
from . import employee_iom
from . import employee_training
from . import hr_sbu_unit
# from . import inherited_hr_employee_public
from . import hr_employee_import_fix
