# -*- coding:utf-8 -*-
{
    'name': 'Payroll',
    'version': '1.0.0',
    'sequence': 1,
    'category': 'Human Resources',
    'summary': 'Payroll for odoo v17',
    'description': """Payroll for odoo v17 """,
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': [
        # 'hr_contract',
        'custom_hr_employee',
        'hr_holidays',
        'hr_work_entry',
        'mail',
        # 'web_dashboard',
        'custom_account_day_book'
    ],
    'data': [
        'security/hr_payroll_security.xml',
        'security/ir.model.access.csv',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'wizard/hr_payroll_index_wizard_views.xml',
        'wizard/employee_increment_letter_wizard_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_salary_rule_views.xml',
        # 'wizard/individual_salary_payment_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_payslip_input_views.xml',
        'views/hr_employee_views.xml',
        'data/hr_payroll_sequence.xml',
        'views/hr_payroll_report.xml',
        'data/hr_payroll_data.xml',
        'data/pf_sequences.xml',
        'views/res_config_settings_views.xml',
        'views/report_contributionregister_templates.xml',
        'views/report_payslip_templates.xml',
        'views/hr_work_entry_views.xml',
        'views/hr_leave_views.xml',
        'views/resource_views.xml',
        # 'views/hr_work_entry_template.xml',
        'views/hr_rule_parameter_views.xml',
        'views/hr_payroll_report_views.xml',
        'views/hr_account_settings.xml',
        'views/hr_payroll_menu.xml',
        # 'wizard/salary_payment_wizard_views.xml',
        # 'views/salary_payment_views.xml',
        'views/hr_contract_update_views.xml',
        'report/employee_increment_letter_tmpl.xml',
        'views/inherited_hr_punishment_inherit_hr_payroll_views.xml',
        'views/inherited_employee_increment_decrement_history_inherit_hr_employee.xml',
        'views/hr_contract_particular_settings_views.xml',
        # 'views/pf_loan_policy_views.xml',
        # 'views/inherited_account_move_inherit_hr_payroll.xml',
        # 'views/pf_accounts_day_book.xml',
        # 'wizard/pf_statement_wizard_views.xml',
        # 'report/pf_statement_report_tmpl.xml',
        # 'wizard/wppf_statement_wizard_views.xml',
        # 'report/wppf_statement_report_tmpl.xml',
        'report/report_contract_update_list_tmpl.xml',
    ],
    'demo': ['data/hr_payroll_demo.xml'],
    'qweb': [
        "static/src/xml/payslip_tree_views.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
