{
    'name': 'Custom HR Resignation',
    'version': "1.0.0",
    'category': "Human Resources",
    'sequence': 1,
    'summary': "Handle the resignation process of the employee for Odoo v17",
    'description': """Manages insurance amounts for employees to be deducted from salary for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['custom_hr_employee', 'mail'],
    # 'demo': ['data/demo_data.xml'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        #'data/resign_employee.xml',
        'views/hr_employee.xml',
        'views/resignation_view.xml',
        'views/approved_resignation.xml',
        'views/resignation_sequence.xml',
        'views/hr_resignation_notice_period_setting.xml',
        'views/hr_separation_type_settings_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
