from . import inherited_hr_recruitment_inherit_hr_recruitment
from . import hr_applicant_dependent
from . import hr_applicant_siblings
from . import hr_applicant_academic
from . import hr_applicant_training
from . import hr_applicant_languages
from . import hr_applicant_experience
from . import hr_applicant_activities
from . import hr_applicant_relatives
