{
    'name': 'Custom HR Transfer',
    'version': "1.0.0",
    'category': "Human Resources",
    'sequence': 1,
    'summary': "Handle the transfer process of the employee for Odoo v17",
    'description': """Handle the transfer process of the employee for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['hr_salary_advance', 'custom_hr_attendance_sheet','custom_hr_leave'],
    'data': [
        'views/hr_transfer_views.xml',
        'views/hr_transfer_seq.xml',
        'views/company_api_settings_views.xml',
        'views/inter_company_transfer_history_views.xml',
        'views/inherited_hr_employee_inherited_hr_transfer_views.xml',
        'report/employee_transfer_report.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
