{
    'name': 'Custom Common Settings',
    'version': '1.0.0',
    'category': 'Settings',
    'sequence': 1,
    'summary': 'Common Custom Settings for Odoo v17',
    'description': """Common Custom Settings for Odoo v17""",
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    # 'depends': ['base', 'account', 'contacts', 'crm', 'project', 'mrp', 'survey', 'event', 'fleet', 'lunch', 'stock', 'sale', 'hr', 'hr_timesheet'],
    'depends': ['base', 'account', 'stock', 'hr','purchase'],
    'data': [
        'data/res.lang.csv',
        'data/report_paper_format_data.xml',
        'data/menu_rename.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'views/assets.xml',
        'data/code_sequence_views.xml',
        'views/inherited_base_inherit_common_settings.xml',
        'views/inherited_report_footer_inherit_custom_common_settings.xml',
        'views/inherited_accounting_menu.xml',
        'views/customer_category_views.xml',
        'views/common_settings_views.xml',
        'views/custom_menu_sequence.xml',
        'views/region_list_views.xml',
        'views/division_views.xml',
        'views/district_views.xml',
        'views/thana_views.xml',
        'views/postcode_views.xml',
        # 'views/inherited_res_partner_inherit_custom_common_settings_views.xml',
        'views/inherited_res_users_inherit_custom_common_settings_views.xml',
        'views/customer_type_views.xml',
        'views/report_color_settings_views.xml',
        'views/cheque_book_bank.xml',
        'views/cheque_book_bank_branch.xml',
        'views/inherited_res_company_inherit_custom_common_settings_views.xml',
        'wizards/customer_upload_wizard_views.xml',
        'views/currency_conversion_rate_views.xml',
        'views/internal_company_views.xml',
        'views/bank_account_type.xml',
        'views/bank_account.xml',
        'views/common_menu_views.xml',
        'views/company_unit_views.xml',
    ],
    'qweb': [
        'static/src/xml/template.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
