{
    'name': "Custom HR Report",
    'version': "1.0.0",
    'category': "Employee Report",
    'sequence': 1,
    'summary': "Custom HR Report for Odoo v17",
    'description': """Custom HR Report for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['hr_presence', 'dev_hr_loan','custom_hr_attendance_sheet','custom_hr_leave','hr_transfer','custom_hr_facilities'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'wizard/date_wise_late_report.xml',
        'wizard/one_time_punch_summary_report.xml',
        'wizard/attendance_summary_report.xml',
        'wizard/new_employee_recruitment_report.xml',
        'wizard/employee_migration_report.xml',
        'wizard/employee_detail_salary_sheet.xml',
        'wizard/department_wise_employee_salary_summary_sheet.xml',
        'wizard/employee_resign_report_wizard_views.xml',
        'wizard/employee_advance_salary_summary_report_wizard_views.xml',
        'wizard/loan_report_wizard_views.xml',
        'wizard/night_food_allowance_report_wizard_views.xml',
        'wizard/month_wise_lefty_report_wizard_views.xml',
        'wizard/area_deduct_adjust_salary_report_wizard_views.xml',
        'wizard/employee_resign_salary_sheet_wizard_views.xml',
        'wizard/employee_salary_sheet_wizard_views.xml',
        'wizard/date_wise_late_early_report.xml',
        'wizard/employee_pf_report_wizard_views.xml',
        'wizard/daily_attendance_sheet_wizard_views.xml',
        'wizard/employee_overtime_report_wizard.xml',
        'wizard/employee_length_of_service_report.xml',
        'wizard/location_wise_employee_salary_summary_report_wizard_views.xml',
        'wizard/employee_pf_details_report.xml',
        'wizard/employee_pf_summery_report.xml',
        'wizard/probationary_employee_report_wizard_views.xml',
        'wizard/employee_leave_encashment_wizard.xml',
        'wizard/unallocated_leave_report_wizard_views.xml',
        'wizard/fringe_benefits_report_wizard_views.xml',
        'wizard/employee_leave_report_wizard_views.xml',
        'wizard/employee_confirmation_report_wizard_views.xml',
        'reports/date_wise_employee_late_report.xml',
        'reports/attendance_summary_report.xml',
        'reports/one_time_punch_employee_summary_report.xml',
        'reports/new_employee_recruitment_report.xml',
        'reports/employee_migration_report.xml',
        'reports/employee_detail_salary_sheet.xml',
        'reports/department_wise_employee_salary_sheet_report.xml',
        'reports/employee_resign_report_tmpl.xml',
        'reports/employee_advance_salary_summary_report_tmpl.xml',
        'reports/loan_report_template.xml',
        'reports/night_food_allowance_report_tmpl.xml',
        'reports/month_wise_lefty_report_tmpl.xml',
        'reports/area_deduct_adjust_salary_report_tmpl.xml',
        'reports/employee_resign_salary_sheet_tmpl.xml',
        'reports/employee_salary_sheet_report.xml',
        'reports/date_wise_employee_late_early_report.xml',
        'reports/employee_pf_report_tmpl.xml',
        'reports/daily_attendance_sheet_tmpl.xml',
        'reports/employee_overtime_report_tmpl.xml',
        'reports/employee_length_of_service_report_templ.xml',
        'reports/location_wise_employee_salary_summary_report_tmpl.xml',
        # 'reports/employee_pf_details_report_tmpl.xml',
        'reports/employee_pf_summery_report_tmpl.xml',
        'reports/probationary_employee_report_tmpl.xml',
        'reports/employee_leave_encashment_wizard_tmpl.xml',
        'reports/unallocated_leave_report_tmpl.xml',
        'reports/fringe_benefits_report_tmlp.xml',
        'reports/employee_leave_report_tmpl.xml',
        'reports/employee_confirmation_report_tmpl.xml',
        'reports/extra_office_time_2h_pdf_report_template.xml',
        'reports/extra_office_time_more2h_pdf_report_template.xml',
        'wizard/employee_extra_office_time_report_wizard.xml',
        'wizard/salary_details_sheet.xml',
        'wizard/month_wise_employee_pf_report_wizard_views.xml',
        'wizard/month_wise_employee_loan_report_wizard_views.xml',
        'wizard/employee_badge_print_report_wizard_views.xml',
        'wizard/leave_emp_attendance_sheet_wizard_views.xml',
        'reports/tiffin_bill_report_tmpl.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
