from . import account_account
from . import account_asset
from . import account_followup
from . import account_journal
from . import account_move
from . import credit_limit
from . import product_template
from . import res_config_settings
from . import res_partner
from . import multiple_invoice
from . import multiple_invoice_layout
from . import recurring_payments
from . import account_payment
from . import res_company
from . import acc_cost_center
from . import inherited_account_move_inherit_base_account_kit
