# -*- coding: utf-8 -*-
from . import gc_erm_mixin
from . import gc_status_history
from . import gc_service_catalog
from . import gc_team
from . import gc_checklist_template
from . import gc_approval_matrix
from . import gc_lead
from . import gc_survey
from . import gc_boq
from . import gc_technical_report
from . import gc_proposal
from . import gc_work_order
from . import gc_procurement
from . import gc_installation
from . import res_partner
from . import res_config_settings
from . import sale_order
from . import purchase_order
from . import stock_picking
from . import account_move
