{
    'name': "Custom HR Employee Requisition",
    'version': "1.0.0",
    'category': "Employee Recruitment",
    'sequence': 1,
    'summary': "Employee Recruitment Requisition Module for Odoo v17",
    'description': """Through this module eligible employee can make requisition to recruit new employee.""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['custom_hr_employee'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/inherited_hr_employee_inherit_hr_employee_requisition_views.xml',
        'views/employee_requisition_views.xml',
        'reports/hr_employee_requisition_print_views.xml',
        'reports/hr_employee_requisition_print_view_new.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
