# -*- coding: utf-8 -*-
################################################################################
{
    'name': 'Odoo17 Dynamic Accounts  Reports',
    'version': '17.0.1.0.0',
    'category': 'Accounting',
    'summary': "Odoo17 Dynamic Accounts  Reports, Dynamic Financial Reports with drill down and filters–"
               "Community Edition",
    'description': "This module creates dynamic Accounting General Ledger, Trial"
                   "Balance, Balance Sheet, Proft and Loss, Cash Book, Partner"
                   "Ledger, Aged Payable, Aged Receivable, Bank book and Tax"
                   "Reports in Odoo 17 community edition, Reporting, Odoo17 Accounting, odoo17 reporting, odoo17, odoo17 accounts reports",
    'author': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': ['base_accounting_kit'],
    'data': [
        'security/ir.model.access.csv',
        'views/accounting_report_views.xml',
        'views/account_books_title_views.xml',
        'views/account_report_config_views.xml',
        'views/res_company_view.xml',
        'views/inherited_account_account_inherit_acc_dynamic_rpt_views.xml',
        'report/trial_balance.xml',
        'report/general_ledger_templates.xml',
        'report/financial_report_template.xml',
        'report/partner_ledger_templates.xml',
        'report/financial_reports_views.xml',
        'report/balance_sheet_report_templates.xml',
        'report/bank_book_templates.xml',
        'report/aged_payable_templates.xml',
        'report/aged_receivable_templates.xml',
        'report/tax_report_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'dynamic_accounts_report/static/src/xml/general_ledger_view.xml',
            'dynamic_accounts_report/static/src/xml/trial_balance_view.xml',
            'dynamic_accounts_report/static/src/xml/cash_flow_templates.xml',
            'dynamic_accounts_report/static/src/xml/bank_flow_templates.xml',
            'dynamic_accounts_report/static/src/xml/profit_and_loss_templates.xml',
            'dynamic_accounts_report/static/src/xml/balance_sheet_template.xml',
            'dynamic_accounts_report/static/src/xml/partner_ledger_view.xml',
            'dynamic_accounts_report/static/src/xml/aged_payable_report_views.xml',
            'dynamic_accounts_report/static/src/xml/aged_receivable_report_views.xml',
            'dynamic_accounts_report/static/src/xml/tax_report_views.xml',
            'dynamic_accounts_report/static/src/css/accounts_report.css',
            'dynamic_accounts_report/static/src/js/general_ledger.js',
            'dynamic_accounts_report/static/src/js/trial_balance.js',
            'dynamic_accounts_report/static/src/js/cash_flow.js',
            'dynamic_accounts_report/static/src/js/bank_flow.js',
            'dynamic_accounts_report/static/src/js/profit_and_loss.js',
            'dynamic_accounts_report/static/src/js/balance_sheet.js',
            'dynamic_accounts_report/static/src/js/partner_ledger.js',
            'dynamic_accounts_report/static/src/js/aged_payable_report.js',
            'dynamic_accounts_report/static/src/js/aged_receivable_report.js',
            'dynamic_accounts_report/static/src/js/tax_report.js',
        ],
    },
    'images': ['static/description/banner.png'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
