{
    'name': "Custom ZK Attendance Device",
    'version': '1.0.0',
    'category': 'Attendance',
    'summary': """Custom ZK Attendance Device for Odoo v17""",
    'description': """Custom ZK Attendance Device for Odoo v17""",
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': ['hr_attendance', 'custom_zk_attendance_base', 'custom_hr_leave'], #'hr_holidays_exclude_include_weekend'
    'data': [
        'data/scheduler_data.xml',
        'data/attendance_state_data.xml',
        'data/mail_template_data.xml',
        'security/module_security.xml',
        'security/ir.model.access.csv',
        'views/menu_view.xml',
        'views/attendance_device_views.xml',
        'views/attendance_state_views.xml',
        'views/device_user_views.xml',
        'views/hr_attendance_views.xml',
        'views/inherited_hr_employee_views.xml',
        'views/user_attendance_views.xml',
        'views/attendance_activity_views.xml',
        'views/rostering_shift_settings_views.xml',
        'views/rostering_monthly_shift_views.xml',
        'views/rostering_alter_shift_views.xml',
        'views/finger_template_views.xml',
        'wizard/attendance_wizard.xml',
        'wizard/employee_upload_wizard.xml',
        'wizard/manual_attendance_wizard_views.xml',
        'wizard/manual_absence_wizard_views.xml',
        #'views/employee_attendance_sheet_line_views.xml',
        # 'wizard/employee_attendance_sheet_line_wizard_views.xml',
        'wizard/update_manual_reason_note_wizard_views.xml',
        'wizard/import_attendace_data_wizard_views.xml',
        #'wizard/attendance_extra_data_clean_wizard_views.xml',
        # 'views/manual_absent_views.xml',
        # 'views/manual_weekend_alter_views.xml',
        #'views/over_time_view.xml',
        'views/shift_management_views.xml',
        'views/shift_management_request_views.xml',
        'views/shift_management_exchange_views.xml',
        #'views/batch_attendance_process_views.xml',
        'wizard/batch_shift_plan_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'custom_zk_attendance_device/static/src/js/*',
            'custom_zk_attendance_device/static/src/xml/*',
        ]
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
