{
    'name': 'Custom Employee Letters',
    'version': "1.0.0",
    'category': "HR Employee",
    'sequence': 1,
    'summary': "Letter format for HR for Odoo v17",
    'description': """Issued letter format for HR, which send to employee on different purposes for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['custom_hr_employee'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/letter_template_views.xml',
        'views/employee_letters_views.xml',
        'views/inherited_hr_employee_views.xml',
        'reports/employee_letter_without_letter_head_report_views.xml',
        'reports/employee_letter_with_letter_head_report_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
