{
    'name': 'Odoo CRM Social Media Lead Form Dashboard App',
    'version': '16.0.0',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    "website": "http://www.pragtech.co.in",
    'category': 'Other',
    'summary': 'Crm odoo dashboard social media facebook instagram linkedin twitter google adwords tik tok campaigns facebook forms lead generation capture leads ad campaigns lead forms lead import dynamic dashboard Odoo CRM Social Media Lead Form Ads Campaign Integration App',
    'description': "Odoo CRM Social Media Lead Form Ads Campaign Integration App",
    'depends': ['crm'],
    "data": [
        'security/social_dashboard_security.xml',
        'views/social_menu_view.xml',
    ],
    'images': ['static/description/gif-Odoo-lead-forms-ad-integrati.gif'],
    'live_test_url': 'https://www.pragtech.co.in/company/proposal-form.html?id=103&name=odoo-lead-form-ad-integration',
    'license': 'OPL-1',
    'price': 49.00,
    'currency': 'USD',
    'auto_install': False,
    'installable': True,
}
