{
    'name': 'Custom Stock',
    'version': '1.1.1',
    'category': 'Inventory',
    'sequence': 1,
    'summary': 'Custom Stock for Odoo v17',
    'description': """Custom Stock for Odoo v17""",
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': ['custom_product_common', 'purchase_stock', 'base_accounting_kit'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        # 'views/assets.xml',
        'views/inherited_res_company_inherit_common_views.xml',
        'views/inherited_res_partner_inherit_stock_views.xml',
        'views/stock_picking_inherit_views.xml',
        'views/inherited_stock_location_inherit_custom_stock_views.xml',
        'views/minimum_stock_list_views.xml',
        'views/mini_product_inventory_adjustment_views.xml',
        'wizards/check_barcode_details_wizard_views.xml',
        'wizards/stock_batch_scrap.xml',
        'wizards/stock_mrr_report_wizard.xml',
        'wizards/current_stock_report_wizard.xml',
        'wizards/inventory_adjustment_report_wizard_views.xml',
        'wizards/scrap_report_wizard_views.xml',
        'wizards/barcode_wise_current_stock_report_wizard_views.xml',
        'wizards/inventory_transfer_report_wizard_views.xml',
        'wizards/inventory_minimum_stock_report_wizard_views.xml',
        'reports/stock_mrr_report_views.xml',
        'reports/current_stock_report_views.xml',
        'reports/barcode_wise_current_stock_report_tmpl.xml',
        'reports/barcode_wise_current_stock_report_without_cost_tmpl.xml',
        'reports/inventory_transfer_report_tmpl.xml',
        'reports/scrap_report_tmpl.xml',
        'reports/inventory_minimum_stock_report_tmpl.xml',
        'wizards/mini_inventory_adjustment_wizard_views.xml',
        'views/inherited_stock_move_inherit_custom_stock.xml',

        # 'views/shop_type_views.xml',
        # 'views/landowner_details_views.xml',
        # 'views/store_godown_views.xml',
        # 'views/store_zone_views.xml',
        # 'views/godown_owner_details_views.xml',
        # 'views/inherited_picking_type_inherit_stock.xml',
        # 'wizards/challan_qty_wizard.xml',
        # 'wizards/on_date_stock_report_wizard_views.xml',
        # 'wizards/sale_order_product_adjustment_wizard.xml',
        # 'reports/inherited_stock_report_inherit_custom_stock.xml',
        # 'reports/stock_individual_mrr_report_views.xml',
        # 'reports/stock_individual_mrr_without_amount_report_views.xml',
        # 'reports/inherited_stock_deliveryslip_inherit_stock.xml',
        # 'reports/report_deliveryslip_with_amount.xml',
        # 'reports/inherited_report_stockpicking_operations_inherit_custom_stock.xml',
        #'reports/barcode_wise_detail_supplier_report_tmpl.xml',
        # 'reports/inventory_adjustment_report_tmpl.xml',
        # 'reports/inherited_report_stockinventory_inherit_custom_stock.xml',
        # 'reports/on_date_stock_report_tmpl.xml',
        # 'reports/report_stock_journal_tmpl.xml',
        # 'views/inherited_stock_scrap_inherit_custom_stock.xml',
        # 'views/courier_service.xml',
        # 'views/courier_mapping.xml',
        # 'views/inherited_account_move_inherit_custom_stock.xml',
        # 'views/inherited_product_product_inherit_custom_stock.xml',
        # 'views/scheduler_data.xml',
        # 'views/current_stock_history_head_views.xml',
        # 'views/stock_terms_condition_views.xml',
        # 'wizards/inherited_stock_change_standard_price_inherit_custom_stock_wizard_views.xml',
    ],
    # 'qweb': [
    #     'static/src/xml/template.xml',
    # ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3'
}
