{
    'name': 'Custom Product Common',
    'version': '1.0.0',
    'category': 'Product',
    'sequence': 1,
    'summary': 'Custom Product Common for Odoo v17',
    'description': """Custom Product Common for Odoo v17""",
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': ['custom_common_settings', 'base', 'account', 'stock', 'purchase', 'sale_management', 'product'],
    
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'views/assets.xml',
        'views/product_brand_views.xml',
        'views/product_style_views.xml',
        # 'views/inherited_uom_uom_inherit_custom_product_common_views.xml',
        'views/inherited_product_product_inherit_custom_product_common_views.xml',
        'views/inherited_product_template_inherit_custom_product_common_views.xml',
        # 'views/sales_price_update_views.xml',
        # 'views/uom_conversion_rate_views.xml',
        # 'reports/change_price_report.xml',
        # 'wizards/sales_price_update_wizard_views.xml',
        # 'wizards/change_price_report_wizard_views.xml',
        # 'wizards/product_upload_wizard_views.xml',
        'views/product_color_views.xml',
        'views/product_common_name.xml',
        'views/product_gsm_views.xml',
        # 'views/product_size_views.xml',
        # 'views/product_cmt_fob_views.xml',
        # 'views/product_item_group_views.xml',
        # 'wizards/generate_product_barcode_wizard_views.xml',
        # 'wizards/product_detail_view_wizard.xml',
        # 'wizards/product_unreserve_wizard.xml',
        # 'views/inherited_stock_quant_inherit_custom_product_views.xml',
    ],
    # 'qweb': [
    #     'static/src/xml/template.xml',
    # ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3'
}
