from . import hr_salary_rule
from . import browsable_object
from . import hr_contract_particular_settings
from . import hr_contract
from . import hr_employee
from . import res_config_settings
from . import hr_payslip
from . import hr_work_entry
from . import hr_leave
from . import resource
from . import hr_rule_parameter
from . import hr_work_intervals
from . import hr_account_settings
from . import salary_payment
from . import hr_contract_update
from . import inherited_hr_punishment
#from . import pf_loan_policy
# from . import inherited_account_move_inherit_hr_payroll
from . import resource_mixin