from . import common_settings
from . import customer_type
from . import inherited_res_users_inherit_custom_common_settings
from . import report_color_settings
from . import cheque_book_bank
from . import cheque_book_bank_branch
from . import inherited_res_company_inherit_custom_common_settings
from . import currency_conversion_rate
from . import inherited_account_move_inherit_custom_common_settings
from . import internal_company
from . import bank_account_type
from . import bank_account
from . import region_list
from . import division
from . import district
from . import thana
from . import post_code
from . import company_unit
