{
    'name': 'Employee Loan Management',
    'version': '1.0.0',
    'sequence': 1,
    'category': 'Human Resources',
    'summary': 'Employee Loan Management for odoo v17',
    'description': """ Employee Loan Management for odoo v17 """,
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': ['provident_fund'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/loan_menu_views.xml',
        'wizard/emp_loan_early_settle_remission_wizard_views.xml',
        'wizard/loan_reschedule_wizard_views.xml',
        'wizard/loan_reject_reason_view.xml',
        'views/hr_loan_view.xml',
        'data/salary_structure.xml',
        'data/ir_sequence_data.xml',
        'views/loan_emi_view.xml',
        'views/hr_employee_view.xml',
        'views/employee_loan_type_views.xml',
        'report/employee_loan_template.xml',
        'report/report_menu.xml',
        'edi/skip_installment_mail_template.xml',
        'views/pay_slip_view.xml',
        'wizard/import_loan_views.xml',
        'wizard/import_logs_view.xml',
        'views/dev_skip_installment.xml',
        'views/hr_loan_dashbord.xml',
        'views/loan_document.xml',
        'views/loan_report_views.xml',
        'views/loan_remission_type_view.xml',
        'views/loan_installment_views.xml',
        'report/loan_application_form_report_view.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}

