{
    'name': 'Employee Bonuses',
    'version': "17.0.0.0.1",
    'category': "Human Resources",
    'sequence': 140,
    'summary': "HR Employee Bonuses for Odoo v17",
    'description': """HR Employee Bonuses for Odoo v17""",
    'author': "Nelsis Tech Limited",
    'company': "Nelsis Tech Limited",
    'maintainer': "Nelsis Tech Limited",
    'website': 'https://nelsistech.com/',
    'depends': ['dev_hr_loan'],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/hr_bonus_menu.xml',
        'views/employee_bonus_type.xml',
        'views/bonus_settings_views.xml',
        'wizards/employee_bonus_payslip_wizard_views.xml',
        'views/employee_bonus.xml',
        'wizards/batch_employee_bonus_wizard_views.xml',
        'wizards/employee_bonus_sheet_wizard_views.xml',
        'views/batch_employee_bonus_views.xml',
        'reports/employee_bonus_sheet_tmpl.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}