{
    'name': "HR Attendance Sheet And Policies",
    'category': 'Human Resource',
    'sequence': 1,
    'version': '1.0.0',
    'summary': """Managing  Attendance Sheets for Employees""",
    'description': """Employees Attendance Sheet Management""",
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': 'https://nelsistech.com/',
    'depends': ['base',
                'hr_payroll',
                # 'hr_holidays',
                'hr_attendance',
                'custom_zk_attendance_device',
                # 'custom_hr_report'
                'hr_resignation'
                ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/scheduler_data.xml',
        'wizard/change_att_data_view.xml',
        'views/hr_attendance_sheet_view.xml',
        'views/hr_attendance_policy_view.xml',
        'views/hr_contract_view.xml',
        'views/hr_public_holiday_view.xml',
        'data/data.xml',
        'wizard/daily_attendance_statistic_report_wizard_views.xml',
        'wizard/attendance_sheet_checkin_checkout_wizard.xml',
        'views/menu_views.xml',
        'report/daily_attendance_statistic_report_tmpl.xml',
        'wizard/batch_attendance_sheet_wizard_views.xml',
        'views/batch_attendance_sheet_views.xml',
        'report/daily_attendance_report.xml',
        'views/inherited_hr_attendance_views.xml',
        'views/batch_attendance_process_views.xml',
        'views/manual_absent_views.xml',
        'views/manual_weekend_alter_views.xml',
        'views/inherited_hr_employee_views.xml',
        'wizard/attendance_extra_data_clean_wizard_views.xml',
        'wizard/employee_attendance_sheet_line_wizard_views.xml',
        'views/employee_attendance_sheet_line_views.xml',
        'views/over_time_view.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
