{
    'name': 'Custom Accounting Day Book',
    'version': '1.0.0',
    'summary': 'Custom Accounting Day Book for Odoo v17',
    'sequence': 1,
    'description': """Custom Accounting Day Book for Odoo v17""",
    'category': 'Accounting',
    'author': 'Nelsis Tech Limited',
    'company': 'Nelsis Tech Limited',
    'maintainer': 'Nelsis Tech Limited',
    'website': "https://nelsistech.com/",
    'depends': ['dynamic_accounts_report', 'stock', 'base_accounting_kit'],
    'data': [
        'security/ir.model.access.csv',
        'views/cheque_book_view.xml',
        'views/day_book_view.xml',
        'views/inherited_res_partner_inherit_day_book.xml',
        'views/inherited_account_journal_inherit_custom_account_day_book_view.xml',
        'views/budget_particular_settings_views.xml',
        'views/budget_particular_views.xml',
        'views/inherited_account_account_tag_inherit_custom_account_day_book_views.xml',
        'reports/cheque_book_report.xml',
        'reports/day_book_report.xml',
        'reports/voucher_report.xml',
        'reports/report_journal_entries_view.xml',
        'reports/inherited_report_payment_receipt_templates_inherit_custom_account_day_book.xml',
        #'wizard/day_book_print_wizard_views.xml',
        'wizard/budget_head_add_wizard_views.xml',
        'wizard/budget_particular_report_wizard_views.xml',
        'views/month_wise_account_summary_report_list_views.xml',
        'wizard/month_wise_account_summary_report_wizard_views.xml',
        'reports/budget_particular_summary_report_tmpl.xml',
        'reports/budget_particular_details_report_tmpl.xml',
        'wizard/project_costing_report_wizard_views.xml',
        'reports/project_costing_report_tmpl.xml',
        'views/menus.xml'
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'uninstall_hook': 'uninstall_hook',
    'license': 'LGPL-3'
}
