# -*- coding: utf-8 -*-
from . import real_estate_land_owner
from . import real_estate_land
from . import real_estate_land_ownership
from . import real_estate_land_agreement
from . import real_estate_project
from . import real_estate_building
from . import real_estate_block
from . import real_estate_floor
from . import real_estate_unit
from . import real_estate_unit_charge
from . import real_estate_project_link
from . import real_estate_project_budget
from . import real_estate_budget_allocation
from . import real_estate_budget_transfer
from . import real_estate_work_package
from . import real_estate_boq
from . import real_estate_boq_line
from . import real_estate_contractor
from . import real_estate_contractor_bill
from . import real_estate_requisition
from . import real_estate_requisition_line
from . import real_estate_site_report
from . import real_estate_qc_checklist_template
from . import real_estate_qc_checklist_template_line
from . import real_estate_qc_inspection
from . import real_estate_qc_inspection_line
from . import real_estate_defect
from . import real_estate_project_readiness_link
from . import real_estate_unit_readiness_link
from . import res_partner_customer_link
from . import real_estate_booking
from . import real_estate_sale_agreement
from . import real_estate_unit_booking_link
from . import real_estate_project_sales_link
from . import real_estate_installment_plan
from . import real_estate_installment
from . import real_estate_collection
from . import res_partner_ledger_link
from . import real_estate_unit_installment_link
from . import real_estate_rental_agreement
from . import real_estate_rent_schedule
from . import real_estate_unit_rental_link
from . import real_estate_collection_rental_link
from . import real_estate_handover
from . import real_estate_handover_checklist_line
from . import real_estate_unit_handover_link
from . import real_estate_project_handover_link
from . import real_estate_handover_warranty_link
from . import real_estate_warranty
from . import real_estate_unit_warranty_link
from . import res_partner_warranty_link
from . import real_estate_dashboard
from . import real_estate_project_profitability_link
