# -*- coding: utf-8 -*-
from odoo import models, fields, api
from odoo.exceptions import ValidationError, UserError


class RealEstateSaleAgreement(models.Model):
    """The binding sale agreement for a unit, usually following a
    confirmed Booking. Activating it (a) re-checks the 'one active
    booking/agreement per unit' rule and (b) moves the Unit to Sold.
    Installment scheduling is intentionally out of scope here - it is
    Phase 6, which will read total_price/down_payment/number_of_installments
    off this record rather than duplicating them."""
    _name = 'real.estate.sale.agreement'
    _description = 'Real Estate Property Sale Agreement'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name = 'name'
    _order = 'id desc'

    name = fields.Char(string='Agreement Number', copy=False, tracking=True,
                        default='New', readonly=True)
    customer_id = fields.Many2one('res.partner', string='Customer', required=True,
                                   tracking=True, ondelete='restrict')
    project_id = fields.Many2one('real.estate.project', string='Project',
                                  related='unit_id.project_id', store=True, readonly=True)
    unit_id = fields.Many2one('real.estate.unit', string='Unit', required=True,
                               tracking=True, ondelete='restrict')
    booking_id = fields.Many2one('real.estate.booking', string='Source Booking',
                                  domain="[('customer_id', '=', customer_id), ('unit_id', '=', unit_id)]")

    agreement_date = fields.Date(string='Agreement Date', default=fields.Date.context_today)
    total_price = fields.Monetary(string='Total Price', required=True)
    discount = fields.Monetary(string='Discount')
    net_price = fields.Monetary(string='Net Price', compute='_compute_net_price', store=True)

    booking_amount = fields.Monetary(string='Booking Amount')
    down_payment = fields.Monetary(string='Down Payment')
    installment_amount = fields.Monetary(
        string='Installment Amount',
        help='Indicative per-installment amount; the actual schedule is '
             'generated by the Installment Plan in a later phase.')
    number_of_installments = fields.Integer(string='Number of Installments')
    frequency = fields.Selection([
        ('monthly', 'Monthly'),
        ('quarterly', 'Quarterly'),
        ('half_yearly', 'Half-Yearly'),
        ('yearly', 'Yearly'),
        ('custom', 'Custom'),
        ('milestone', 'Milestone Based'),
    ], string='Frequency', default='monthly')

    handover_date = fields.Date(string='Expected Handover Date')
    terms = fields.Html(string='Terms')
    attachment_ids = fields.Many2many(
        'ir.attachment', 'real_estate_sale_agreement_ir_attachment_rel',
        'agreement_id', 'attachment_id', string='Documents')

    state = fields.Selection([
        ('draft', 'Draft'),
        ('active', 'Active'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ], string='State', default='draft', tracking=True, required=True, copy=False)

    company_id = fields.Many2one(related='unit_id.company_id', store=True, readonly=True)
    currency_id = fields.Many2one(related='company_id.currency_id', readonly=True)

    @api.depends('total_price', 'discount')
    def _compute_net_price(self):
        for rec in self:
            rec.net_price = rec.total_price - rec.discount

    @api.onchange('unit_id')
    def _onchange_unit_id(self):
        if self.unit_id:
            self.total_price = self.unit_id.final_price

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') == 'New':
                vals['name'] = self.env['ir.sequence'].next_by_code(
                    'real.estate.sale.agreement') or 'New'
        return super().create(vals_list)

    @api.constrains('down_payment', 'total_price')
    def _check_down_payment(self):
        for rec in self:
            if rec.down_payment and rec.down_payment > rec.total_price:
                raise ValidationError(
                    'Down Payment cannot exceed Total Price on agreement "%s".' % rec.name)

    def action_activate(self):
        for rec in self:
            if rec.state != 'draft':
                raise UserError('Only draft agreements can be activated.')
            rec.unit_id.check_single_active_booking(exclude_agreement_id=rec.id)
        self.write({'state': 'active'})
        for rec in self:
            rec.unit_id.write({'status': 'sold'})
            if rec.booking_id and rec.booking_id.state == 'confirmed':
                rec.booking_id.write({'sale_agreement_id': rec.id})

    def action_complete(self):
        for rec in self:
            if rec.state != 'active':
                raise UserError('Only active agreements can be completed.')
        self.write({'state': 'completed'})

    def action_cancel(self):
        for rec in self:
            if rec.state == 'cancelled':
                raise UserError('This agreement is already cancelled.')
        for rec in self:
            was_active = rec.state == 'active'
            rec.write({'state': 'cancelled'})
            if was_active and rec.unit_id.status == 'sold':
                rec.unit_id.write({'status': 'available'})

    def action_reset_to_draft(self):
        self.write({'state': 'draft'})
